version: '3'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount the frontend directory for development
      - ./frontend:/app/frontend
    environment:
      - PORT=8000
    restart: unless-stopped
    command: ["--port", "8000"]
    networks:
      - vqa-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/vqa-annotations
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - vqa-network

  # MongoDB service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - vqa-network

volumes:
  mongo-data:

networks:
  vqa-network:
    driver: bridge
