name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # メインブランチにプッシュされたときに実行

# GitHub Actionsに必要な権限を設定
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 全履歴をフェッチ

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create build directory
        run: mkdir -p build

      - name: Create Firebase config
        run: |
          echo "const firebaseConfig = {
            apiKey: \"${{ secrets.FIREBASE_API_KEY || 'YOUR_API_KEY' }}\",
            authDomain: \"${{ secrets.FIREBASE_AUTH_DOMAIN || 'your-project-id.firebaseapp.com' }}\",
            projectId: \"${{ secrets.FIREBASE_PROJECT_ID || 'your-project-id' }}\",
            storageBucket: \"${{ secrets.FIREBASE_STORAGE_BUCKET || 'your-project-id.appspot.com' }}\",
            messagingSenderId: \"${{ secrets.FIREBASE_MESSAGING_SENDER_ID || 'YOUR_MESSAGING_SENDER_ID' }}\",
            appId: \"${{ secrets.FIREBASE_APP_ID || 'YOUR_APP_ID' }}\"
          };" > frontend/js/firebase-config.js

      - name: Copy frontend files to build directory
        run: cp -r frontend/* build/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build  # デプロイするフォルダ
          branch: gh-pages  # デプロイ先のブランチ
          clean: true  # デプロイ前に既存のファイルをクリーン
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub Tokenを使用
